module.exports = {
    getCSRF     : require('./getCSRF'),
    getMuffin   : require('./getMuffin'),
    postLogin   : require('./postLogin'),
    getLogout   : require('./getLogout'),
    getClassroom : require('./getClassroom'),
    getAssignment : require('./getAssignment'),
    getAssignmentExists : require('./getAssignmentExists'),
    postCreateClassroom : require('./postCreateClassroom'),
    postRetrieveClassrooms : require('./postRetrieveClassrooms'),
    postDeleteClassroom: require('./postDeleteClassroom'),
    postUploadClassroomCSV: require('./postUploadClassroomCSV'),
    postRetrieveStudents: require('./postRetrieveStudents'),
    postAddStudent: require('./postAddStudent'),
    postCreateAssignment: require('./postCreateAssignment'),
    postRetrieveAssignments: require('./postRetrieveAssignments'),
    postRetrieveStudentAssignments: require('./postRetrieveStudentAssignments'),
    postAutoSaveProgress: require('./postAutoSaveProgress'),

}