const router = require('express').Router()
const controller = require('../controllers')

router.get('/csrf',controller.getCSRF)
router.get('/muffin/:crumble',controller.getMuffin)
router.post('/login',controller.postLogin)
router.get('/logout',controller.getLogout)
router.get('/check_classroom_exists',controller.getClassroom)
router.get('/check_student_exists',controller.getStudent)
router.post('/create_classroom',controller.postCreateClassroom)
router.post('/retrieve_classrooms',controller.postRetrieveClassrooms)
router.post('/delete_classroom',controller.postDeleteClassroom)
router.post('/upload_classroom_csv',controller.postUploadClassroomCSV)
router.post('/retrieve_students',controller.postRetrieveStudents)
router.post('/add_student',controller.postAddStudent)
router.post('/create_assignment',controller.postCreateAssignment)
router.post('/retrieve_assignments',controller.postRetrieveAssignments)
router.get('/check_assignment_exists',controller.getAssignment)
router.post('/retrieve_student_assignments',controller.postRetrieveStudentAssignments)
router.get('/check_assignment_exists_for_student',controller.getAssignmentExists)
router.post('/auto_save_progress',controller.postAutoSaveProgress)
router.post('/retrieve_completions_for_assignment',controller.postRetrieveCompletionsForAssignment)
router.post('/change_due_date',controller.postChangeAssignmentDue)
router.post('/delete_assignment',controller.postDeleteAssignment)
router.post('/change_classroom_name',controller.postChangeClassroomName)
router.post('/change_student_data',controller.postChangeStudentData)
router.post('/delete_student',controller.postDeleteStudent)
router.post('/retrieve_student_records',controller.postRetrieveStudentRecords)

module.exports = router;